### PR TITLE
Look for the schema files in the right place

### LINKED ISSUE #1928: Unable to resolve path to XML schemas when SimpleSAMLphp is a composer dependency of another project
**Specifics of your environment**
1. Are you acting as SP/IdP/proxy?
SP

2. SimpleSAMLphp: What version are you using?
2.1.1

3. PHP: What version are you using?
8.1.23

4. Platform: unix or Windows?
unix

5. Webserver: Apache/Nginx/ISS?
Unit/Nginx

**Describe the bug**
When I try to validate a known valid XML file using `XML::isValid`, I get a schema validation error:
```
Schema validation failed on XML string: level=1,code=1549,line=0,col=0,msg=failed to load external entity "/app/vendor/simplesamlphp/simplesamlphp/vendor/simplesamlphp/saml2/schemas/saml-schema-metadata-2.0.xsd" level=2,code=1757,line=0,col=0,msg=Failed to locate the main schema resource at '/app/vendor/simplesamlphp/simplesamlphp/vendor/simplesamlphp/saml2/schemas/saml-schema-metadata-2.0.xsd'.
```

The issue seems to be in where SimpleSAMLphp is expecting to find the metadata. `XML::isValid` attempts to find the schema in `vendor/simplesamlphp/saml2/schemas`. This seems to assume that the directory structure is something like this:
* SimpleSAML application
  * vendor
    * simplesamlphp
      *  saml2

However, in my application, my directory structure looks like this:
* vendor
  * simplesamlphp
    * simplesamlphp
      * SimpleSAML application
    * saml2

I assume this is because I am using SimpleSAMLphp as a dependency of another composer project.

**To Reproduce**
```
# Create a composer project
composer init --name test/test

# Install simplesamlphp
composer require simplesamlphp/simplesamlphp

# Configure simplesamlphp
cp vendor/simplesamlphp/simplesamlphp/config/config.php.dist vendor/simplesamlphp/simplesamlphp/config/config.php
```

Create a simple test PHP file:
```
<?php

use SimpleSAML\Configuration;

require 'vendor/autoload.php';

$config = Configuration::getInstance();
echo $config->resolvePath('vendor/simplesamlphp/saml2/schemas');
```

And execute it:
```
php test.php
```

**Expected behavior**
The path would resolve to: `/app/vendor/simplesamlphp/saml2/schemas`

**Actual behavior**
The path resolved to: `/app/vendor/simplesamlphp/simplesamlphp/vendor/simplesamlphp/saml2/schemas`
This path does not exist.

**Additional context**
I am using SimpleSAMLphp with a Drupal application with the https://www.drupal.org/project/simplesamlphp_auth project. SimpleSAMLphp is a dependency of the Drupal module. My project declares the Drupal module as a dependency making SimpleSAMLphp an indirect dependency.

If I set `basedir` in `config.php` (i.e. `'basedir' => '/app'`), it fixes this error...but then SimpleSAMLphp can no longer find any of its modules.

### PR DESCRIPTION
**Pull request by tvdijen**
Closes #1928

### CODE REVIEW

File: src/SimpleSAML/Configuration.php [hunk 1]
```diff
@@ -558,6 +559,25 @@ public function getPathValue(string $name, ?string $default = null): ?string
...
+     *
+     * @return string The absolute path to the vendor directory. This path will always end with a slash.
+     */
+    public function getVendorDir(): string
+    {
+        if (file_exists(dirname(__FILE__, 3) . '/vendor')) {
+            return dirname(__FILE__, 3) . '/vendor/';
+        } else {
+            // SSP is loaded as a library.
+            return dirname(__FILE__, 3) . '/../../vendor/';
```
Comment (mediabounds) [inline src/SimpleSAML/Configuration.php:576]: I think we need to go one more level higher.

I tried this test:
```
(new XML)->isValid('<root></root>', 'saml-schema-metadata-2.0.xsd');
```

And got this PHP warning:
```
PHP Warning:  DOMDocument::schemaValidate(): Invalid Schema in /app/test/vendor/simplesamlphp/simplesamlphp/src/SimpleSAML/Utils/XML.php on line 364
PHP Stack trace:
PHP   1. {main}() /app/test/test.php:0
PHP   2. SimpleSAML\Utils\XML->isValid($xml = '<root></root>', $schema = 'saml-schema-metadata-2.0.xsd') /app/test/test.php:8
PHP   3. DOMDocument->schemaValidate($filename = '/app/test/vendor/simplesamlphp/simplesamlphp/../../vendor/simplesamlphp/saml2/resources/schemas/saml-schema-metadata-2.0.xsd') /app/test/vendor/simplesamlphp/simplesamlphp/src/SimpleSAML/Utils/XML.php:364
Schema validation failed on XML string:
level=1,code=1549,line=0,col=0,msg=failed to load external entity "/app/test/vendor/vendor/simplesamlphp/saml2/resources/schemas/saml-schema-metadata-2.0.xsd"
level=2,code=1757,line=0,col=0,msg=Failed to locate the main schema resource at '/app/test/vendor/vendor/simplesamlphp/saml2/resources/schemas/saml-schema-metadata-2.0.xsd'.
```

```suggestion
            return dirname(__FILE__, 3) . '/../../../vendor/';
```
