### PR TITLE
Reinstate url-based authentication

### LINKED ISSUE #1682: 2.0-rc1 Login page not found
**Describe the bug**
After upgrading from 1.19.3, the URL returned by `SimpleSAML\Auth\Simple::getLoginURL()` displays a cryptic error message:

> The given page was not found. The reason was: The URL wasn't found in the module. The URL was: https://gerben.alisqi.com.test-xxx.platformsh.site/sso/module.php/core/login/gerben?AuthId=gerben&ReturnTo=https%3A%2F%2Fgerben.alisqi.com.test-xxx.platformsh.site%2F%3Fmod%3Dlogin%26ssoLogin

image

The `config.php` was changed as described in the changelog.

### PR DESCRIPTION
**Pull request by tvdijen**
Restores the functionality to trigger authentication by URL.
To not expose individual authsources like we did before, a check was added to test the passed authsource to be saml:SP. Those are the only ones safe to expose like this.

Closes #1682

### CODE REVIEW

File: modules/saml/src/Controller/ServiceProvider.php [hunk 1]
```diff
@@ -105,6 +105,46 @@ public function setAuthUtils(Utils\Auth $authUtils): void
     }
 
 
+    /**
+     * Start single sign-on for an SP identified with the specified entityID
```
Comment (thijskh) [inline modules/saml/src/Controller/ServiceProvider.php:109]: not "entityID" but "auth source ID"

File: modules/saml/src/Controller/ServiceProvider.php [hunk 2]
```diff
@@ -105,6 +105,46 @@ public function setAuthUtils(Utils\Auth $authUtils): void
...
+         * Setting up the options for the requireAuth() call later..
+         */
+        $httpUtils = new Utils\HTTP();
+        $options = [
+            'ReturnTo' => $httpUtils->checkURLAllowed($returnTo),
+        ];
+
+        /**
+         * Allows a saml:idp query string parameter specify the IdP entity ID to be used
+         * as used by the DiscoJuice embedded client.
```
Comment (thijskh) [inline modules/saml/src/Controller/ServiceProvider.php:137]: DiscoJuice is long dead... so do we need this?

**Review by thijskh — APPROVED** [review]

File: modules/saml/src/Controller/ServiceProvider.php (hunk 2 above)
Comment (tvdijen) [reply modules/saml/src/Controller/ServiceProvider.php:137]: The setting itself seems not specific to DiscoJuice.. It is referenced in `modules/saml/docs/sp.md`

Comment (thijskh) [reply modules/saml/src/Controller/ServiceProvider.php:137]: Maybe just drop it from the comment then... referencing the dead product will likely make the same question arise in the future?

Comment (tvdijen) [reply modules/saml/src/Controller/ServiceProvider.php:137]: I think we can drop the entire code-block since the only references are to the SP authsource.

**Review by thijskh — APPROVED** [review]
Great, let's merge it, if someone misses the option no doubt we will hear about it
